server:
  port: 8095
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthentificationFilter

        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthentificationFilter



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true